name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Executa diariamente à meia-noite
  workflow_dispatch:     # Permite executar manualmente pela aba "Actions"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: luanna-galliza
          repository: luanna-galliza/luanna-galliza
          outputs: |
            dist/github-contribution-grid-snake.svg
          color_snake: '#ff79c6'  # Rosa neon estilo cyberpunk
          color_dots: '#1a1b26,#414868,#7aa2f7,#bb9af7,#c0caf5'  # Paleta Tokyo Night

      - name: Publicar no branch `output`
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

